### ISSUE TITLE
Google Query limit queries to 32 words

### ISSUE THREAD

**Issue by jrkb6** [naynco/nayn.org#18]
Google search services limit the exclusion keywords up to 32. Since there are more than 32 websites in BLOCKED_WEBSITES, filtering works for only the first 32 of these sites. I found Google serves a custom search engine but it looks like you have to be connected with a google account to change settings. Looking for an alternative way. Any ideas?

**Comment by SysEng** [comment]
Well, i made some research about custom search engine feature after first pull request and tried some examples, there are two options that we can try but both of them need google accounts as you mentioned.

* Use custom search engine with exluded web sites added manually from custom search engine control panel (picture 1)
  * This one is more suitable for current situtation, in current situtation; when typing to search text input and hit enter, it redirect to google.com with query parameters, this one is also works pretty much same way, but someone or maybe couple of people needs to be authenticate to manage custom search engine control panel to add to website for exclusion. (picture 2)
   * Maybe there are some theming issues, can't handle same view with nayn.org/search page (like dark/light, responsive etc.) because it embed javascript file to place search bar input to the page. 
   * Plus, this one is free :)

* Use custom search engine JSON API with excluded web sites added dynamically with XMLHttpRequest GET method
   * With pure javascript, can be implemented custom search engine JSON API and send exluded websites with **siteSearch** parameter and also add **siteSearchFilter** parameter with value **e** (means excluded)
   * Process returned JSON data within page and show the results, plus need to making pagination below the page to provide querying next pages. (that actually means "making copy of google search webpage")
   * Advantages of these options, maybe with locale storage or caching etc., user can be able to customize blocked websites.
   * This is not free, after 100 queries per day,  $5 per 1000 queries and there is 10.000 query limit per day, it means $50 per day with fully usage.

* [JSON API example response](https://gist.github.com/SysEng/945916da3f248cf8c8a203e30b75040e)
* [picture 1 for excluding web sites](https://i.ibb.co/86XCCPy/image.png)
* [picture 2 for authenticate users](https://i.ibb.co/RTVttcv/image.png)
* [JSON API parameters list](https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list)

**Comment by hmert** [comment]
@SysEng I've already created [custom search engine](https://cse.google.com/cse?cx=006151674876054365721:ukffccic1e3). But experience is changed with this ui. But as you mentioned "it is free", and NAYN has no revenue :)

For those who want to implement here is our custom search engine's embed code.

```
<script async src="https://cse.google.com/cse.js?cx=006151674876054365721:ukffccic1e3"></script>
<div class="gcse-searchresults-only"></div>
```

I've talk with DuckDuckGo team for creating nayn.search on top of their platform. If nayn.search gets a traction, they will consider.

PS: I really do not expect such a demand. Just like you, not a few, contributors have made great job. Thank you.

**Comment by jrkb6** [comment]
Thanks for your responses. 
@SysEng 
Forcing people to create their own custom ( or programmable by google's own definition) search engine is not a feasible way to do. I might be looking at the creation of the custom search engine via direct API ( if it's possible). After creating a custom search engine with blocked web sites there is no need to use another service such as nayn.co/search or extensions. But it's a bit over-complicated for simple or lazy users like me :).

For the second option, your claim makes sense.  Making copy of google search ui is meaningless.
>   * Process returned JSON data within page and show the results, plus need to making pagination below the page to provide querying next pages. (that actually means "making copy of google search webpage")

@hmert 
I thought creating a web extension with the custom search engine so that I can use up to 100 queries till I find another way, However, I couldn't pass the google content-security-policy since custom-search-engine uses an inline script from google.

Finally, I've accepted the 32-word query limitations of the google search. With these conditions, I thought we can give preference to the user so she can determine these 32 bad new sites to be blocked. Now I'm adding the UI components( hopefully I don't break current UI :) ) to view and update these sites to the project. Also, I decided to save user preferences to the window.localstorage in order to keep updated block sites. 

I guess I will open a pull request in a few days for these updates. Hope to see your reviews. Thanks.
